---
title: "RWorksheet_Sanceda-4B"
output: pdf_document
date: "2024-12-09"
---


```{r}
#1
vector <- c(1, 2, 3, 4, 5)
matrix_ <- matrix(0, nrow = 5, ncol = 5)


for (i in 1:5) {
  for (j in 1:5) {
    matrix_[i, j] <- vector [abs(i - j) + 1]
  }
}

matrix_

```

```{r}
#2
rows <- 5


for (i in 1:rows) {
  cat(rep("*", i), sep = " ")
  cat("\n")
}
```

```{r}
#3
fnum <- as.integer(readline(prompt = "Enter first number for fibonacci sequence(1 - 500): "))
fibonacci <- c(0,1)

repeat {
  next_fib <- sum(tail(fibonacci, 2))
  if (next_fib > 500) {
    break
  }
  fibonacci <- c(fibonacci, next_fib)
}

output <- fibonacci[fibonacci >= fnum]
cat("Fibonacci sequence from",fnum, "up to 500:", output, "\n")
```

```{r}
#4
#a
library(readxl)
data <- read.csv("Shoes_Tble.csv")
head(data, 6)
```

```{r}
#b
fdata <- subset(data, Gender == "F")
mdata <- subset(data, Gender == "M")

females <- nrow(fdata )
males <- nrow(mdata)

cat("Number of Female observations:", females , "\n")
cat("Number of Male observations:",males , "\n")
```
```{r}
#c
G_Count <- c(Males = 14, Females = 14)


barplot(
  G_Count, names.arg = "Number of Individuals", 
  main = "Number of Males and Females in Household Data", 
  col = c("green", "violet"))

legend("topright",                                  
       legend = names(G_Count),              
       fill = c("green", "violet"))                  

```

```{r}
#5
colors <- c("white", "pink", "purple", "black")
x <- c(60, 10, 5, 25)
mylabel <- c("Food", "Electricity", "Savings", "Miscellaneous")
pie(x, label = mylabel, main = "Dela Cruz Family Monthly Expenses", init.angle = 50, col = colors)
```

```{r}
#6
#a
data(iris)
str(iris)
# The output is the structure of the object. 
```

```{r}
#b
mean <- c(
  Mean_Sepal_Length = mean(iris$Sepal.Length),
  Mean_Sepal_Width = mean(iris$Sepal.Width),
  Mean_Petal_Length = mean(iris$Petal.Length),
  Mean_Petal_Width = mean(iris$Petal.Width)
)

mean
```

```{r}
#c
colors <- c("white", "lightblue", "gray")
Species <- table(iris$Species)

pie(Species, main = "Species Distribution in Iris Dataset", init.angle = 75, col = colors)
```

```{r}
#d
data(iris)
Sts <- iris[iris$Species == "Setosa", ]
Vrsclr <- iris[iris$Species == "Versicolor", ]
Vgnca <- iris[iris$Species == "Virginica", ]

setosa <- tail(Sts, 6)
versicolor <- tail(Vrsclr, 6)
virginica <- tail(Vgnca, 6)

cat("Setosa:\n")
print(setosa)

cat("\n Versicolor:\n")
print(versicolor)

cat("\nVirginica:\n")
print(virginica)

```

```{r}

data(iris)

plot(iris$Sepal.Length, iris$Sepal.Width,
     col = c("red","yellow","black"),
     pch = 19,
     xlab = "Sepal Length",
     ylab = "Sepal Width",
     main = "Iris Dataset",
     sub = "Sepal width and length by Species"
)

legend("topright", legend = levels(iris$Species),
       col = 1:3, pch = 19)                  


```   

```{r}
#7
library(readxl)
alexa_dtst <- read_excel("~/alexa_file.xlsx")
alexa_dtst


table(alexa_dtst$variation)
  

  alexa_dtst$variation <- gsub("Black\\s+Dot", "Black Dot", alexa_dtst$variation)
  alexa_dtst$variation <- gsub("Black\\s+Plus", "Black Plus", alexa_dtst$variation)
  alexa_dtst$variation <- gsub("Black\\s+Show", "Black Show", alexa_dtst$variation)
  alexa_dtst$variation <- gsub("Black\\s+Spot", "Black Spot", alexa_dtst$variation)
  alexa_dtst$variation <- gsub("White\\s+Dot", "White Dot", alexa_dtst$variation)
  alexa_dtst$variation <- gsub("White\\s+Plus", "White Plus", alexa_dtst$variation)
  alexa_dtst$variation <- gsub("White\\s+Show", "White Show", alexa_dtst$variation)
  alexa_dtst$variation <- gsub("White\\s+Spot", "White Spot", alexa_dtst$variation)
  

  table(alexa_dtst$variation)
  
  
```

```{r}
#b
library(dplyr)


vrtns_count <-alexa_dtst %>%
  count(variation, name = "Total")


save(vrtns_count, file = "variations.RData")


print(vrtns_count)
```

```{r}
#c
library(ggplot2)

load("variations.RData")


ggplot(vrtns_count, aes(x = variation, y = Total, fill = variation)) +
  geom_bar(stat = "identity") +
  ggtitle("Total Count of Alexa Variations") +
  xlab("Variation") +
  ylab("Total Numbers") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_fill_brewer(palette = "Set3")
```

```{r}
#d
vrtns_count$Category <- ifelse(grepl("Black", vrtns_count$variation), "Black Variants", 
                                    ifelse(grepl("White", vrtns_count$variation), "White Variants", NA))

vrnts <-vrtns_count %>% filter(!is.na(Category))


ggplot(vrnts, aes(x = variation, y = Total, fill = variation)) +
  geom_bar(stat = "identity") +
  facet_wrap(~ Category, scales = "free_x") +  
  ggtitle("Counts of Alexa Black and White Variants") +
  xlab("Variation") +
  ylab("Total Numbers") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_fill_brewer(palette = "Set2") 
```