---
title: "RWorksheet_Sanceda#4a"
output:
  pdf_document: default
  word_document: default
date: "2024-11-17"
---

```{r}
#1.
#a. The data displays the Shoe Size, Height, and Gender.

    ShoeSize <- c(6.5,9.0,8.5,8.5,10.5,7.0,9.5,9.0,13.0,7.5,10.5,8.5,12.0,10.5,13.0,11.5,8.5,5.0,10.0,6.5,7.5,8.5,10.5,8.5,10.5,11.0,9.0,13.0)

    Height <-c(66.0,68.0,64.5,65.0,70.0,64.0,70.0,71.0,72.0,64.0,74.5,67.0,71.0,71.0,77.0,72.0,59.0,62.0,72.0,66.0,64.0,67.0,73.0,69.0,72.0,70.0,69.0,70.0)
    
    Gender <- c("F","F","F","F","M","F","F","F","M","F","M","F","M","M","M","M","F","F","M","F","F","M","M","F","M","M","M","M")
    
    Shoes_Tble <- data.frame(ShoeSize, Height, Gender)
    Shoes_Tble
    
#b.
    
    Male <- subset(Shoes_Tble, Gender == "M", select = c(ShoeSize, Gender, Height))
    Male
    
    Female <- subset(Shoes_Tble, Gender == "F", select = c(ShoeSize, Gender, Height))
    Female
    
    
#c.
    
    Mean_Size <- mean(ShoeSize)
    Mean_Size
    
    Mean_Height <- mean(Height)
    Mean_Height
    
#d. Yes, because the bigger or taller you are the more likely your shoe size is also bigger.
    
```

```{r}
#2. 

    Months <- c("March", "April", "January", "November", "January", "September", "October", "September", "November", "August", "January", "November", "November", "February", "May", "August", "July", "December", "August", "August", "September", "November", "February", "April")

    Factor_Mnths <- factor(Months)
    Factor_Mnths
    
    assign("Factor_Months_Vector",Factor_Mnths)
    Factor_Months_Vector
    
```
```{r}
#3.

    summary(Months)

    summary(Factor_Months_Vector)
    
```
```{r}
#4. 

    Direction <- c("East", "West", "North")
    Frequency <- c(1,4,3)
    DirFreq <- data.frame(Direction, Frequency)
    DirFreq
    
    new_order_data <- factor(Direction ,levels = c("East","West","North"))
print(new_order_data)

```

```{r}
#5.

    Excel <- read.table("import_march.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE)
    Excel
    
```

```{r}
#6.

    N <- readline(prompt = "Enter a number 1 to 50:")
    if(N == 20){
      print("TRUE")
    }else if(N <= 50 && N >= 0){
      N
    }else{
      print("The number is way beyond the range of 1 and 50.")
    }
```
```{r}
      
#7.
   min_bills <- function(price) {
  bills <- c(1000, 500, 200, 100, 50)
  

  count <- 0
  
  for (bill in bills) {
    if (price <= 0) {
      break
    }
    count <- count + floor(price / bill)
    
    price <- price %% bill
  }
  
  return(count)
}


snack_price <- as.integer(readline(prompt = "Enter the price of the snack (divisible by 50): "))
if (is.na(snack_price) %% 50 == 0) {
  cat("Minimum number of bills needed:", min_bills(snack_price), "\n")
} else {
  cat("The price must be divisible by 50.\n")
}
```



```{r}
#8
#a
Grades <- data.frame (Name = c("Annie", "Thea", "Steve", "Hanna"),
                       Grade_1 = c(85, 65, 75, 95),
                       Grade_2 = c(65, 75, 55, 75),
                       Grade_3 = c(85, 90, 80, 100),
                       Grade_4 = c(100, 90, 85, 90)
                       )
Grades
```


```{r}
#b
for (i in 1:nrow(Grades)) {
  ascore <- sum(Grades[i, 2:5]) / 4
  if (ascore > 90) {
    cat(Grades$Name[i], "'s average grade this semester is", ascore, "\n")
  }
}
```


```{r}
#c
for (j in 2:ncol(Grades)) {
  T_avg <- sum(Grades[, j]) / nrow(Grades)
  if ( T_avg  < 80) {
    cat("The", colnames(Grades)[j], "test was difficult.\n")
  }
}
```

```{r}
#d
for (i in 1:nrow(Grades)) {
  H_grade <- Grades[i, 2]
  for (j in 3:5) {
    if (Grades[i, j] > H_grade) {
      H_grade <- Grades[i, j]
    }
  }
  if (H_grade > 90) {
    cat(Grades$Name[i], "'s highest grade this semester is", H_grade, "\n")
  }
}
```

