---
title: "Rworksheet_Sanceda#3"
output: pdf_document
date: "2024-09-30"
---
```{r}

#1. 
#a.
    
    LETTERS
    letters
    
    Lttrs <- LETTERS[1:11]
    Lttrs
#b.

    oddletters <- LETTERS[seq(1, 26 ,2)]
    oddletters
    
#c.

    vowels <- LETTERS[c(1, 5, 9, 15, 21)]
    vowels
    
#d.

    last5 <- tail(letters, 5)
    last5
    
#e. 

    lttrs <- letters[15:24]
    lttrs
```

```{r}

#2.
#a.

    City <- c("Tuguegarao City", "Manila", "Iloilo City", "Tacloban", "Samal Island", "Davao City")
    City
    
#b.

    apriltemp <- c(42, 39, 34, 34, 30, 27)
    apriltemp
    
#c.

    hahaha <- data.frame(City, apriltemp)
    hahaha
    
#d.

    names(hahaha) <- c("City", "Temperature")
    hahaha
    
#e.

    str(hahaha)
    
#f.

    hahaha[3:4, ]
    
#g.

    hahaha[which.max(hahaha$Temperature),]
    hahaha[which.min(hahaha$Temperature),]
    
```
```{r}

#Matrices

#a.

    mx <- matrix(c(1,2,3,4,5,6,7,8,11,12,13,14), nrow = 3, ncol = 4)
    mx
    
#b.

    mtrx <- mx * 2
    mtrx
    
#c.
    
     mx[2,]
    
#d. 
    
     mx[1:2, 3:4]
    
#e.
     
     mx[3, 2:3]
     
#f. 
     
     mx[, 4]
     
#g.
     
     rownames(mx) <- c("Isa", "Dalawa", "Tatlo")
     colnames(mx) <- c("Uno", "Dos", "Tres", "Quatro")
     mx
     
#h.
     
     dim(mx) <- c(6,2)
     mx
```
```{r}
#Arrays

#a.

      nArray <- array(rep(c(1, 2, 3, 6, 7, 8, 9, 0, 3, 4, 5, 1), 2), c(2, 4, 3))
      nArray
      
#b.
      
      dim(nArray)
      
      #My array has 3 dimensions
      
#c.
      
      dimnames(nArray)[[1]] <- c("a", "b")
      dimnames(nArray)[[2]] <- c("A", "B", "C", "D")
      dimnames(nArray)[[3]] <- c("1st - Dimensional Array", "2nd - Dimensional Array", "3rd - Dimensional Array")
      nArray

```